config/routes.rb
DonationsChallenge::Application.routes.draw do
  devise_for :users

  root "donations#index"

  resources :users do
    resources :donations, only: [:index, :new, :create]
    resources :items, only: [:index, :new, :create]
    resources :vouchers, only: [:index, :new, :create]
    resources :experiences, only: [:index, :new, :create]
  end

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donatable, polymorphic: true
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  has_one :donation, as: :donatable, dependent: :destroy
  accepts_nested_attributes_for :donation

  validates :primary_contact_name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_one :donation, as: :donatable, dependent: :destroy
  accepts_nested_attributes_for :donation


  validates :height, presence: true
  validates :width, presence: true
  validates :weight, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :donations, dependent: :destroy
end

app/models/voucher.rb
class Voucher < ActiveRecord::Base
  has_one :donation, as: :donatable, dependent: :destroy
  accepts_nested_attributes_for :donation
  
  validates :expiration_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @items = Item.where(user_id: current_user.id).includes(:donation)
    @vouchers = Voucher.where(user_id: current_user.id).includes(:donation)
    @experiences = Experience.where(user_id: current_user.id).includes(:donation)
    gon.locations = @experiences
  end

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    set_user_id
    if @donation.save
      redirect_to root_path, notice: "Successfully created"
    else
      render :new
    end
  end

  private

  def set_user_id
    @donation.user_id = current_user.id
  end

  def donation_params
    params.require(:donation).permit(:title, :description)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @experiences = Experience.where(user_id: current_user.id)
  end

  def new
    @experience = Experience.new
    @experience.build_donation(donatable_id: params[:id], donatable_type: "Experience")
  end

  def create
    @experience = Experience.new(experience_params)
    set_user_id
    if @experience.save
      redirect_to root_path, notice: "Successfully created"
    else
      render :new
    end
  end

  private

  def set_user_id
    @experience.user_id = current_user.id
  end

  def experience_params
    params.require(:experience).permit(:primary_contact_name, :latitude, :longitude, donation_attributes: [:title, :description])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @items = Item.where(user_id: current_user.id)
  end

  def new
    @item = Item.new
    @item.build_donation(donatable_id: params[:id], donatable_type: "Item")
  end

  def create
    @item = Item.new(item_params)
    set_user_id
    if @item.save
      redirect_to root_path, notice: "Successfully created"
    else
      render :new
    end
  end

  private

  def set_user_id
    @item.user_id = current_user.id
  end

  def item_params
    params.require(:item).permit(:height, :width, :weight, donation_attributes: [:title, :description])
  end
end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @vouchers = Voucher.where(user_id: current_user.id)
  end

  def new
    @voucher = Voucher.new
    @voucher.build_donation(donatable_id: params[:id], donatable_type: "Voucher")
  end

  def create
    @voucher = Voucher.new(voucher_params)
    set_user_id
    if @voucher.save
      redirect_to root_path, notice: "Successfully created"
    else
      render :new
    end
  end

  private

  def set_user_id
    @voucher.user_id = current_user.id
  end

  def voucher_params
    params.require(:voucher).permit(:expiration_date, donation_attributes: [:title, :description])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/donations/_form.html.erb
<%= form_for [current_user, @donation] do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :title %><br />
  <%= f.text_field :title, placeholder: "Title", id: "donation_title" %><br />
  <%= f.label :description %><br />
  <%= f.text_area :description, placeholder: "Description", id: "donation_description" %><br />
  <%= f.submit "Submit" %>
<% end %>

app/views/donations/index.html.erb
<h1>Donations</h1>
<div class="pull-left">
  <%= link_to "Add Item", new_user_item_path(current_user), class: "btn btn-default btn-md " %>
  <%= link_to "Add Voucher", new_user_voucher_path(current_user), class: "btn btn-default btn-md" %>
  <%= link_to "Add Experience", new_user_experience_path(current_user), class: "btn btn-default btn-md" %>
</div>
<div class="clearfix"></div>
<% unless @items.empty? %>
  <h3>Items</h3>
  <% @items.each do |i| %>
    <p>
      <%= i.donation.title %>: <%= i.donation.description %><br />
      Height: <%= i.height %><br />
      Width: <%= i.width %><br />
      Weight: <%= i.weight %><br />
    </p>
  <% end %>
<% end %>
<% unless @vouchers.empty? %>
  <h3>Vouchers</h3>
  <% @vouchers.each do |v| %>
    <p>
      <%= v.donation.title %>: <%= v.donation.description %><br />
      Expiration Date: <%= v.expiration_date %><br />
    </p>
  <% end %>
<% end %>
<% unless @experiences.empty? %>
  <h3>Experiences</h3>
  <% @experiences.each do |e| %>
    <p>
      <%= e.donation.title %>: <%= e.donation.description %><br />
      Primary Contact Name: <%= e.primary_contact_name %><br />
      Latitude/Longitude: <%= e.latitude %>, <%= e.longitude %>
    </p>
  <% end %>
  <div id="map-canvas"></div>
<% end %>

<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" %>
<%= javascript_tag do %>
  initialize_maps();
<% end %>

app/views/donations/new.html.erb
<%= render 'donations/form' %>

app/views/experiences/_form.html.erb
<%= form_for [current_user, @experience] do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.fields_for(:donation) do |d| %>
    <%= d.label :title %><br />
    <%= d.text_field :title, placeholder: "Title", id: "experience_title" %><br />
    <%= d.label :description %><br />
    <%= d.text_area :description, placeholder: "Description", id: "experience_description" %><br />
  <% end %>
  <%= f.label :primary_contact_name %><br />
  <%= f.text_field :primary_contact_name, placeholder: "Primary Contact Name", id: "experience_name" %><br />
  <%= f.label :latitude %><br />
  <%= f.number_field :latitude, placeholder: "Latitude", id: "experience_latitude", step: "any" %><br />
  <%= f.label :longitude %><br />
  <%= f.number_field :longitude, placeholder: "Longitude", id: "experience_longitude", step: "any" %><br />

  <%= f.submit "Submit" %>
<% end %>

app/views/experiences/new.html.erb
<%= render 'experiences/form' %>

app/views/items/_form.html.erb
<%= form_for [current_user, @item] do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.fields_for(:donation) do |d| %>
    <%= d.label :title %><br />
    <%= d.text_field :title, placeholder: "Title", id: "item_title" %><br />
    <%= d.label :description %><br />
    <%= d.text_area :description, placeholder: "Description", id: "item_description" %><br />
  <% end %>
  <%= f.label :height %><br />
  <%= f.number_field :height, placeholder: "Height", id: "item_height", step: "any" %><br />
  <%= f.label :width %><br />
  <%= f.number_field :width, placeholder: "Width", id: "item_width", step: "any" %><br />
  <%= f.label :weight %><br />
  <%= f.number_field :weight, placeholder: "Weight", id: "item_weight", step: "any" %><br />

  <%= f.submit "Submit" %>
<% end %>

app/views/items/new.html.erb
<%= render 'items/form' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% unless user_signed_in? %>
  <li>
    <%= link_to "Sign up", new_user_registration_path %>
  </li> 
  <li>
    <%= link_to "Login", new_user_session_path %>
  </li> 
<% else %>
  <li>
    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Donations Challenge" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Donations Challenge" %>">
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/vouchers/_form.html.erb
<%= form_for [current_user, @voucher] do |f| %>
  <% if @voucher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voucher.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @voucher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.fields_for(:donation) do |d| %>
    <%= d.label :title %><br />
    <%= d.text_field :title, placeholder: "Title", id: "voucher_title" %><br />
    <%= d.label :description %><br />
    <%= d.text_area :description, placeholder: "Description", id: "voucher_description" %><br />
  <% end %>
  <%= f.label :expiration_date %><br />
  <%= f.datetime_select :expiration_date, id: "voucher_date" %><br />

  <%= f.submit "Submit" %>
<% end %>

app/views/vouchers/new.html.erb
<%= render 'vouchers/form' %>